def gv

pipeline {

    agent any
    tools {
        maven 'maven-3.9'
    }
    parameters {
        choice( name: 'VERSION', choices: ['1.1.0', '1.2.0', '1.3.0'], description: 'different test versions')
        booleanParam( name: 'executeTest', defaultValue: true, description: '')
    }
    stages {
        stage("init") {
            steps {
                script {
                    gv = load "Jenkinsfile-demo/script.groovy"
                }
            }
        }

        stage("build") {
            steps {
                script {
                    gv.buildApp()
                }
            }
        }

        stage("test") {
            when {
                expression {
                    params.executeTest == true
                }
            }
            steps {
                script {
                    gv.testApp()
                }
            }
        }

        stage("deploy") {
            input {
                message "Select the environment to deploy to: "
                ok "Done"
                parameters {
                    choice( name: 'ENV', choices: ['dev', 'staging', 'prod'], description: 'different envs to deploy to')
                }
            }
            steps {
                script {
                    gv.deployApp()
                    echo "Deploying to ${ENV}"
                }
            }
        }
    }

}
